#GET
https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/releases?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D










###SIMON TEST - works 100% fine
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{
"CustomProperties":[],
"TaskId":3,
"Name":"CWrite book object insert queries",
"Description":"The SQL statement that actually inserts a new book into the system",
"ReleaseId":8,
"TaskTypeId":1,
"TaskPriorityId":1,
"TaskStatusId":3,
"CreatorId":2,
"OwnerId":2,
"ComponentId":1,
"TaskFolderId":3,
"CreationDate":"2020-10-09T13:00:28.532Z",
"StartDate":"2020-12-26T14:00:28.532Z",
"EndDate":"2020-12-29T13:00:28.532Z",
"EstimatedEffort":180,
"ActualEffort":170,
"ProjectedEffort":170,
"RequirementId":4,
"CompletionPercent":100,
"ConcurrencyDate":"2021-04-28T15:24:38.560Z",
"fileUrl":"https://localhost:3000/taskpane.js",
"lineNumber":12332,
"columnNumber":3
}
