##RISKS TEST
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/incidents/1?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{"CustomProperties":[],
"RiskId":1,
"Name":"The v1.1 release may not be ready in time",
"Description":"<p>Due to some resourcing issues, there is a possibility that we will not make the expected go-live date.</p>",
"ReleaseId":4,
"RiskTypeId":4,
"RiskImpactId":2,
"RiskProbabilityId":1,
"RiskStatusId":4,
"CreatorId":2,
"OwnerId":2,
"CreationDate":"2021-01-26T19:00:28.422Z",
"ConcurrencyDate":"2021-04-29T12:42:09.373Z",
"fileUrl":"https://localhost:3000/taskpane.js",
"lineNumber":12340,
"columnNumber":3}

### MAOE
https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/incidents/1?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D


###works fine
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{"CustomProperties":[{"PropertyNumber":1,"IntegerValue":1},{"PropertyNumber":2,"IntegerValue":13}],"TaskId":1,"Name":"3. Develop new book entry screen","Description":"<p>Create a new dynamic page that allows the user to enter the details of a new book</p>\n","ReleaseId":1,"TaskTypeId":1,"TaskPriorityId":1,"TaskStatusId":2,"CreatorId":13,"OwnerId":13,"TaskFolderId":1,"CreationDate":"2020-10-19T16:00:28.532Z","StartDate":"2021-01-05T15:00:28.532Z","EndDate":"2021-01-05T15:00:28.532Z","EstimatedEffort":480,"ActualEffort":440,"ProjectedEffort":920,"RemainingEffort":480,"ConcurrencyDate":"2021-04-28T15:34:38.427Z","fileUrl":"https://localhost:3000/taskpane.js","lineNumber":12332,"columnNumber":3}

###does not work
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{"TaskId":2,"Name":"BCreate book object insert method","Description":"Code the business object that inserts a new book row in the database","ReleaseId":8,"TaskTypeId":1,"TaskPriorityId":1,"TaskStatusId":3,"CreatorId":2,"OwnerId":2,"ComponentId":1,"TaskFolderId":3,"CreationDate":"2020-10-09T04:00:28.532Z","StartDate":"2020-12-26T04:00:28.532Z","EndDate":"2020-12-27T04:00:28.532Z","EstimatedEffort":300,"ActualEffort":320,"ProjectedEffort":320,"RequirementId":4,"CompletionPercent":100,"ConcurrencyDate":"2021-04-28T20:10:41.710Z","fileUrl":"https://localhost:3000/taskpane.js","lineNumber":12332,"columnNumber":3}

#############SIMON

#get to update the concurrency date 
https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks/2?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D



###works fine
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{"CustomProperties":[{"PropertyNumber":1,
"IntegerValue":1},{"PropertyNumber":2,
"IntegerValue":13}],
"TaskId":1,
"Name":"3. Develop new book entry screen",
"Description":"<p>Create a new dynamic page that allows the user to enter the details of a new book</p>\n",
"ReleaseId":1,
"TaskTypeId":1,
"TaskPriorityId":1,
"TaskStatusId":2,
"CreatorId":13,
"OwnerId":13,
"TaskFolderId":1,
"CreationDate":"2020-10-19T16:00:28.532Z",
"StartDate":"2021-01-05T15:00:28.532Z",
"EndDate":"2021-01-05T15:00:28.532Z",
"EstimatedEffort":480,
"ActualEffort":440,
"ProjectedEffort":920,
"RemainingEffort":480,
"ConcurrencyDate":"2021-04-28T20:30:01.367Z"}

###does not work
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{
"TaskId":2,
"Name":"BCreate book object insert method",
"Description":"Code the business object that inserts a new book row in the database",
"ReleaseId":8,
"TaskTypeId":1,
"TaskPriorityId":1,
"TaskStatusId":3,
"CreatorId":2,
"OwnerId":2,
"ComponentId":1,
"TaskFolderId":3,
"CreationDate":"2020-10-09T04:00:28.532Z",
"StartDate":"2020-12-26T04:00:28.532Z",
"EndDate":"2020-12-27T04:00:28.532Z",
"EstimatedEffort":300,
"ActualEffort":320,
"ProjectedEffort":320,
"RequirementId":4,
"CompletionPercent":100,
"ConcurrencyDate":"2021-04-28T20:36:52.617Z"
}



###SIMON TEST - works 100% fine
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{
"CustomProperties":[],
"TaskId":3,
"Name":"CWrite book object insert queries",
"Description":"The SQL statement that actually inserts a new book into the system",
"ReleaseId":8,
"TaskTypeId":1,
"TaskPriorityId":1,
"TaskStatusId":3,
"CreatorId":2,
"OwnerId":2,
"ComponentId":1,
"TaskFolderId":3,
"CreationDate":"2020-10-09T13:00:28.532Z",
"StartDate":"2020-12-26T14:00:28.532Z",
"EndDate":"2020-12-29T13:00:28.532Z",
"EstimatedEffort":180,
"ActualEffort":170,
"ProjectedEffort":170,
"RequirementId":4,
"CompletionPercent":100,
"ConcurrencyDate":"2021-04-28T15:24:38.560Z",
"fileUrl":"https://localhost:3000/taskpane.js",
"lineNumber":12332,
"columnNumber":3}



###BRUNO TEST
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/tasks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{
"CustomProperties":null,
"TaskId":3,
"Name":"CWrite book object insert queries",
"Description":"The SQL statement that actually inserts a new book into the system",
"ReleaseId":8,
"TaskTypeId":1,
"TaskPriorityId":1,
"TaskStatusId":3,
"CreatorId":2,
"OwnerId":2,
"ComponentId":1,
"TaskFolderId":3,
"CreationDate":"2020-10-09T13:00:28.532Z",
"StartDate":"2020-12-26T14:00:28.532Z",
"EndDate":"2020-12-29T13:00:28.532Z",
"EstimatedEffort":180,
"ActualEffort":170,
"ProjectedEffort":170,
"RequirementId":4,
"CompletionPercent":100,
"RemainingEffort": 0,
"ProjectId": 1,
"ConcurrencyDate":"2021-04-28T22:57:47.057Z",
"fileUrl":"https://localhost:3000/taskpane.js",
"lineNumber":12332,
"columnNumber":3
}

