### GET
https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/9/incidents/77100?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D

###WORKS FINE
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/9/incidents/77100?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D 
content-type: application/json
Accept: application/json

{
    "CustomProperties":
    [
        {"PropertyNumber":3,
        "DateTimeValue":"2021-04-22T12:59:59.999Z"}
    ],
    "IncidentId":77100,
    "Name":"Live Feed out of frequency",
    "Description":"<p>The live feed of channel 2 EST is not in the specified spectro.The live feed of channel 2 EST is not in the specified spectro.</p>n",
    "IncidentTypeId":9,
    "IncidentStatusId":9,
    "PriorityId":7,
    "OpenerId":2,
    "DetectedReleaseId":59,
    "CreationDate":"2021-04-02T02:27:42.786Z",
    "StartDate":"2021-04-01T12:59:59.999Z",
    "EstimatedEffort":180,
    "RemainingEffort":180,
    "ConcurrencyDate": "2021-04-01T17:27:42.787Z",
    "fileUrl":"https://localhost:3000/taskpane.js",
    "lineNumber":12354,
    "columnNumber":3
}

