### GET
https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/risks/6?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D


###WORKS FINE
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/risks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{
    "CustomProperties": [],
    "RiskId": 7,
    "Name": "Test From Excel",
    "Description": "DESC TEST",
    "ReleaseId": 2,
    "RiskTypeId": 4,
    "RiskImpactId": 2,
    "RiskProbabilityId": 2,
    "RiskStatusId": 3,
    "CreatorId": 2,
    "OwnerId": 2,
    "ComponentId": 1,
    "CreationDate": "2021-04-11T12:00:00.000Z",
    "RiskExposure": 12,
    "ConcurrencyDate": "2021-04-30T12:51:52.610Z",
    "fileUrl": "https://localhost:3000/taskpane.js",
    "lineNumber": 12354,
    "columnNumber": 3
}

### DOES NOT WORK
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/risks?username=administrator&api-key=%7BD0D25647-F6C9-4355-8B83-F21666B84BD1%7D
content-type: application/json
Accept: application/json

{
    "CustomProperties": [],
    "RiskId": 6,
    "Name": "Test From Excel",
    "Description": "DESC TEST",
    "ReleaseId": 2,
    "RiskTypeId": 4,
    "RiskImpactId": 2,
    "RiskProbabilityId": 2,
    "RiskStatusId": 3,
    "CreatorId": 2,
    "OwnerId": 2,
    "ComponentId": 1,
    "CreationDate": "2021-04-11T12:00:00.000Z",
    "RiskExposure": 12,
    "ConcurrencyDate": "2021-04-30T12:51:52.127Z",
    "fileUrl": "https://localhost:3000/taskpane.js",
    "lineNumber": 12354,
    "columnNumber": 3
}