##Modelo do Simon
PUT http://gallifrey.corp.inflectra.com/Spira/services/v6_0/RestService.svc/projects/138/test-sets/?username=administrator&api-key={B9050F75-C5E6-4244-8712-FBF20061A976}
content-type: application/json
Accept: application/json

{
  "TestSetId": 87,
  "IndentLevel": null,
  "TestSetStatusId": 1,
  "CreatorId": 1,
  "OwnerId": null,
  "ReleaseId": null,
  "AutomationHostId": null,
  "TestRunTypeId": 1,
  "RecurrenceId": null,
  "Name": "beta set",
  "Description": null,
  "CreationDate": "2021-03-30T16:34:38.043Z",
  "LastUpdateDate": "2021-03-30T16:34:42.873Z",
  "PlannedDate": null,
  "ExecutionDate": null,
  "CountPassed": 0,
  "CountFailed": 0,
  "CountCaution": 0,
  "CountBlocked": 0,
  "CountNotRun": 0,
  "CountNotApplicable": 0,
  "CreatorName": "System Administrator",
  "OwnerName": null,
  "ProjectName": "shb_2021-03-30T16:29:34.875Z",
  "TestSetStatusName": "Not Started",
  "ReleaseVersionNumber": null,
  "RecurrenceName": null,
  "TestSetFolderId": null,
  "EstimatedDuration": null,
  "ActualDuration": null,
  "IsAutoScheduled": false,
  "IsDynamic": false,
  "DynamicQuery": null,
  "TestConfigurationSetId": null,
  "BuildExecuteTimeInterval": null,
  "ProjectId": 138,
  "ArtifactTypeId": 8,
  "ConcurrencyDate": "2021-03-30T19:44:21.997Z",
  "CustomProperties": [
    {
      "PropertyNumber": 30,
      "StringValue": "test3",
      "IntegerValue": null,
      "BooleanValue": null,
      "DateTimeValue": null,
      "DecimalValue": null,
      "IntegerListValue": null,
      "Definition": {
        "CustomPropertyId": 338,
        "ProjectTemplateId": 113,
        "ArtifactTypeId": 8,
        "Name": "o",
        "CustomList": null,
        "CustomPropertyFieldName": "Custom_30",
        "CustomPropertyTypeId": 1,
        "CustomPropertyTypeName": "Text",
        "IsDeleted": false,
        "PropertyNumber": 30,
        "SystemDataType": "System.String",
        "Options": null
      }
    },
    {
      "PropertyNumber": 31,
      "StringValue": "test4",
      "IntegerValue": null,
      "BooleanValue": null,
      "DateTimeValue": null,
      "DecimalValue": null,
      "IntegerListValue": null,
      "Definition": {
        "CustomPropertyId": 333,
        "ProjectTemplateId": 113,
        "ArtifactTypeId": 8,
        "Name": "p",
        "CustomList": null,
        "CustomPropertyFieldName": "Custom_31",
        "CustomPropertyTypeId": 1,
        "CustomPropertyTypeName": "Text",
        "IsDeleted": false,
        "PropertyNumber": 31,
        "SystemDataType": "System.String",
        "Options": null
      }
    }
  ],
  "IsAttachments": false,
  "Tags": null
}

#GET
https://internal-bruno.spiraservice.net/services/v6_0/RestService.svc/projects/1/test-sets/1?username=administrator&api-key={092DF44E-5F94-4C8B-A1CD-705E44319E6D}


###TEST SET - TESTING PUT*
PUT https://internal-bruno.spiraservice.net/services/v6_0/RestService.svc/projects/1/test-sets/8?username=administrator&api-key={092DF44E-5F94-4C8B-A1CD-705E44319E6D}
content-type: application/json
Accept: application/json

{
    "CustomProperties":
    [
        {
            "PropertyNumber":1,
            "StringValue":"<p>Bla</p>n"
        },
        {"PropertyNumber":2,
        "IntegerListValue":[13]
        }
    ],
    "TestSetId":8,
    "Name":"New TS From Excel",
    "Description":"<p>Sample Description</p>n",
    "ReleaseId":11,
    "TestRunTypeId":1,
    "TestSetStatusId":3,
    "RecurrenceId":3,
    "CreatorId":1,
    "OwnerId":1,
    "TestSetFolderId":2,
    "CreationDate":"2021-04-11T03:27:12.652Z",
    "PlannedDate":"2021-04-12T21:00:00.000Z",
    "ConcurrencyDate":"2021-04-10T19:00:51.320Z"
}

