##tEST
PUT https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/test-cases/22/test-steps?username=administrator&api-key=%7B092DF44E-5F94-4C8B-A1CD-705E44319E6D%7D
content-type: application/json
Accept: application/json

{
    "CustomProperties":[],
    "TestStepId":46,
    "TestCaseId": 22,
    "Description":"bcvb",
    "ExpectedResult":"bcbvc",
    "SampleData":"bcvb",
    "ConcurrencyDate":"2021-05-05T00:33:55.377Z",
    "isSubType":true
}

### GET
https://internal-bruno.spiraservice.net//services/v6_0/RestService.svc/projects/1/test-cases/22/test-steps?username=administrator&api-key=%7B092DF44E-5F94-4C8B-A1CD-705E44319E6D%7D

